services:
  web:
    build: .
    volumes:
      - rails_log:/rails/log
      - rails_storage:/rails/storage
    ports:
      - "3000:3000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/up"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
  queue:
    build: .
    environment:
        RAILS_ENV: production
    command: bash -c "bin/rails db:prepare && bin/rails solid_queue:start"
    depends_on:
      - web
    volumes:
      - rails_log:/rails/log
      - rails_storage:/rails/storage
    healthcheck:
      disable: true

volumes:
  rails_log:
  rails_storage:
