default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  primary:
    <<: *default
    url: <%= ENV.fetch("DATABASE_URL", "postgres://postgres:Xk9mP2vL7nQ4wR8s@db:5432/surf_radio_development") %>
  cache:
    <<: *default
    url: <%= ENV.fetch("CACHE_DATABASE_URL", "postgres://postgres:Xk9mP2vL7nQ4wR8s@db:5432/surf_radio_development_cache") %>
    migrations_paths: db/cache_migrate
  queue:
    <<: *default
    url: <%= ENV.fetch("QUEUE_DATABASE_URL", "postgres://postgres:Xk9mP2vL7nQ4wR8s@db:5432/surf_radio_development_queue") %>
    migrations_paths: db/queue_migrate
  cable:
    <<: *default
    url: <%= ENV.fetch("CABLE_DATABASE_URL", "postgres://postgres:Xk9mP2vL7nQ4wR8s@db:5432/surf_radio_development_cable") %>
    migrations_paths: db/cable_migrate

test:
  primary:
    <<: *default
    url: <%= ENV.fetch("DATABASE_URL", "postgres://postgres:Xk9mP2vL7nQ4wR8s@db:5432/surf_radio_test") %>
  cache:
    <<: *default
    url: <%= ENV.fetch("CACHE_DATABASE_URL", "postgres://postgres:Xk9mP2vL7nQ4wR8s@db:5432/surf_radio_test_cache") %>
    migrations_paths: db/cache_migrate
  queue:
    <<: *default
    url: <%= ENV.fetch("QUEUE_DATABASE_URL", "postgres://postgres:Xk9mP2vL7nQ4wR8s@db:5432/surf_radio_test_queue") %>
    migrations_paths: db/queue_migrate
  cable:
    <<: *default
    url: <%= ENV.fetch("CABLE_DATABASE_URL", "postgres://postgres:Xk9mP2vL7nQ4wR8s@db:5432/surf_radio_test_cable") %>
    migrations_paths: db/cable_migrate

production:
  primary:
    <<: *default
    url: <%= ENV.fetch("DATABASE_URL") %>
  cache:
    <<: *default
    url: <%= ENV.fetch("CACHE_DATABASE_URL") { ENV.fetch("DATABASE_URL").sub(/\/[^\/]*$/, "_cache") } %>
    migrations_paths: db/cache_migrate
  queue:
    <<: *default
    url: <%= ENV.fetch("QUEUE_DATABASE_URL") { ENV.fetch("DATABASE_URL").sub(/\/[^\/]*$/, "_queue") } %>
    migrations_paths: db/queue_migrate
  cable:
    <<: *default
    url: <%= ENV.fetch("CABLE_DATABASE_URL") { ENV.fetch("DATABASE_URL").sub(/\/[^\/]*$/, "_cable") } %>
    migrations_paths: db/cable_migrate
